- name: install postgreSQL
  apt:
    name:
      - postgresql
      - python-psycopg2
    update_cache: true

# find a way to rerun that on an existing machine
- name: create kong ppostgreSQL user
  shell: psql -c "CREATE ROLE kong WITH PASSWORD 'kong'; ALTER ROLE kong WITH LOGIN;"
  become_user: postgres
  ignore_errors: yes

- name: create kong postgreSQL db
  shell: psql -c "CREATE DATABASE kong OWNER kong;"
  become_user: postgres
  ignore_errors: yes
