---
- name: Ensure webroot exists
  file:
    path: "/etc/letsencrypt/live/{{ server_name }}"
    state: directory

- name: Generate self-signed certificates for {{ server_name }}
  shell: openssl req -new -nodes -x509 -subj "/C=FR/ST=Paris/L=Paris/O=IT/CN={{ server_name }}" -reqexts SAN -extensions SAN -config <(cat /etc/ssl/openssl.cnf ; printf '[SAN]\nsubjectAltName=DNS:{{ server_name }}') -days 3650 -keyout /etc/letsencrypt/live/{{ server_name }}/privkey.pem -out /etc/letsencrypt/live/{{ server_name }}/fullchain.pem
  args:
    creates: "/etc/letsencrypt/live/{{ server_name }}/fullchain.pem"
    executable: /bin/bash
  notify: "restart web services"

- name: Check if controller host is a Mac. If so, we will need to manually trust the certificate
  shell: uname
  register: uname
  delegate_to: localhost

- name: Set the switch for certificate registration on Macs
  set_fact:
    register_certificate: "{{ 'Darwin' in uname.stdout }}"

- name: Copy certificate to controller host
  fetch:
    src: "/etc/letsencrypt/live/{{ server_name }}/fullchain.pem"
    dest: "/tmp/{{ server_name }}-fullchain.pem"
    flat: yes
  when: register_certificate | bool

- name: Trust certificate on controller host
  shell: /usr/bin/security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain /tmp/{{ server_name }}-fullchain.pem
  become: true
  when: register_certificate | bool
  delegate_to: localhost
